@startuml

class Colony 
{
    +ColonyResources resources
    +ColonyPopulation population
    +ColonyBuildings buildings
}

class ColonyPopulation 
{
    +List<Citizen> citizens
}

class ColonyBuildings 
{
    +List<Building> buildings
}

class TaskManager
{
    +Queue<ColonyTask> tasks
}



@enduml