@startuml
'https://plantuml.com/class-diagram

package "Resources" 
{

    class Resource 
    {
        +ResourceConfig config
        +int amount
    }
        
    class ResourceConfig 
    {
        +string type
        +string name
    }
}


@enduml