@startuml

state Any
state Idle
state Eat
state Work
state Sleep

Any --> Eat : hunger < n
Any --> Sleep : energy < n

Eat --> Idle : hunger = max
Sleep --> Idle : energy = max

Work --> Idle : !hasWork
Idle --> Work : hasWork

@enduml