@startuml

package "Citizens"
{
    package "Descriptions"
    {
        class CitizensDescription
        {
            +string[] names
            +float startMoveSpeed
            +Dictionary<string, (int, int))> thresholdNeeds
        }
    }

    package "Models"
    {
        class Citizen 
        {
            +int id
            +string name
            +Dictionary<string, Resource> needs
            +CitizenStateMachine stateMachine
            +Vector2 position
            +float moveSpeed
        }
    }
}

@enduml