@startuml

package "Citizens"
{
    package "Configs"
    {
        class CitizensConfig
        {
            +string[] names
            +float startMoveSpeed
        }
    }

    package "Models"
    {
        class Citizen 
        {
            +int id
            +string name
            +Dictionary<string, Resource> needs
            +CitizenStateMachine stateMachine
            +float moveSpeed
            +Vector2 position
        }
    
     package "StateMachine" {
        class CitizenStateMachine {
            +Dictionary<Type, CitizenState> states
            +CitizenState currentState
        }   
        
        abstract class CitizenState 
        {
            
        }
        
        class IdleState 
        {        
            
        }
        
        class MoveState 
        {
            +Vector2 position
        }
        
        class WaitState 
        {
            +Vector2 position
        }
        
        CitizenState <|.. WaitState  
        CitizenState <|.. MoveState  
        CitizenState <|.. IdleState  
        CitizenStateMachine --> CitizenState
        }
    }
}

@enduml