@startuml

package "ColonyOrders"
{
    package "Models"
    {
        class ColonyOrdersPool 
        {
            +Dictionary<string, ColonyOrder> claimedOrders    
            +Dictionary<string, ColonyOrder> availableOrders
        }
        
        class ColonyOrder
        {
            +int id
            +int toBuildingId
            +int fromBuildingId
            +List<int> citizensId
        }
        
        class DeliveryOrder
        {
            Resource resource
        }
        
        ColonyOrdersPool --> ColonyOrder
        DeliveryOrder <|.. ColonyOrder
    }
}

@enduml