@startuml

package "Buildings"
{
    package "Descriptions"{
        
        class BuildingDescriptionCollection 
        {
            +Dictionary<string, BuildingDescription> Descriptions
        }
        
        class BuildingDescription
        {
            +string type
            +string name
        }
        
        class DecorationBuildingDescription
        {
        }
        
        class ProductionBuildingDescription
        {
            +long productionTime        
            +string productionResource
            +int maxResourceAmount
        }
        
        class ServiceBuildingDescription 
        {
            +long serviceTime
            +int maxQueue
            +int maxCitizenAmount
            +string serviceResource
        }
        
        class StorageBuildingDescription 
        {
            +int maxResourceAmount
        }
        
        BuildingDescription <|.. DecorationBuildingDescription  
        BuildingDescription <|.. ProductionBuildingDescription  
        BuildingDescription <|.. ServiceBuildingDescription  
        BuildingDescription <|.. StorageBuildingDescription  
        BuildingDescriptionCollection o--> BuildingDescription 
    }

    package "Models"
    {
        class Building
        {
            +int id
            +Vector2 position
        }
        
        class ProductionBuilding
        {
            +ProductionBuildingDescription Description
            +ColonyOrdersPool ordersPool
            +bool isActive
            +long completeProductionTime
            +Resource resource
        }
        
        class ServiceBuilding
        {
            +ServiceBuildingDescription Description
            +bool isActive
            +Dictionary<int, long> inService
            +Queue<int> waitingQueue
        }
        
        class DecorBuilding
        {
            +DecorBuildingDescription Description
        }
        
        class StorageBuilding
        {
            +StorageBuildingDescription Description
            +Dictionary<string, Resource> resources
        }
        
        Building <|.. ProductionBuilding
        Building <|.. ServiceBuilding
        Building <|.. DecorBuilding
        Building <|.. StorageBuilding
    }
}

@enduml