@startuml

package "Resources" 
{
    package "Descriptions"
    {
        class ResourceDescriptionsCollection
        {
            +Dictionary<string, ResourceDescription> descriptions
        }
            
        class ResourceDescription 
        {
            +string type
            +string name
            +float reductionTime
            +int reductionAmount
        }

        ResourceDescriptionsCollection o--> ResourceDescription 
    }

    package "Models"
    {
        class Resource
        {
            +ResourceDescription description
            +int amount
        }
    }
}

@enduml