@startuml

package "ColonyOrders"
{
    package "Models"
    {
        class ColonyOrdersPool 
        {
            +Queue<ColonyOrder> claimedOrders    
            +Queue<ColonyOrder> availableOrders    
        }
        
        class ColonyOrder
        {
            +int id
            +int toBuildingId
            +int fromBuildingId
            +List<int> citizensId
        }
        
        class DeliveryOrder
        {
            +Resource resource
        }
        
        ColonyOrdersPool --> ColonyOrder
        ColonyOrder <|-- DeliveryOrder
    }
}

@enduml