@startuml

package "Colony" 
{
    
    package "Configs" {
        class ColonyConfig {
        }
    }

    package "Models" {
     class Colony 
        {
            +ColonyConfig config
            +ColonyResources resources
            +ColonyPopulation population
            +ColonyBuildings buildings
        }
        
        class ColonyPopulation 
        {
            +List<Citizen> citizens
        }
        
        class ColonyBuildings 
        {
            +List<Building> buildings
        }
        
        class TaskManager
        {
            +Queue<ColonyTask> tasks
        }
        
        Colony *-- ColonyPopulation
        Colony *-- ColonyBuildings
        Colony *-- TaskManager
    }

}


@enduml