@startuml

package "Colony" 
{
    package "Descriptions" 
    {
        class ColonyDescription 
        {
        }
    }
}
    package "Models" {
    class Colony 
    {
        +ColonyDescription descriptions
        +ColonyPopulation population
        +ColonyBuildings buildings
        +ColonyOrdersPool pool
    }

    class ColonyPopulation 
    {
        +List<Citizen> citizens
    }
    
    class ColonyBuildings 
    {
        +List<ProductionBuilding> productionBuildings
        +List<ServiceBuilding> serviceBuildings
        +List<StorageBuilding> storageBuildings
        +List<DecorBuilding> decorBuildings
    }

    Colony *-- ColonyBuildings
    Colony *-- ColonyPopulation
    }
}

@enduml