@startuml

package "Core"
{
    class Citizen
    class Colony
    class ColonyOrder
    class CitizenStateMachine
    class Building
    class Factory
    class Resource
    
    Colony --> Factory
    Colony --> ColonyOrder
    Factory --> Building
    Factory --> Resource
    Factory --> Citizen
    Citizen --> CitizenStateMachine
}

@enduml