@startuml

package "Resources" 
{
    package "Configs"
    {
        class ResourceConfigCollection
        {
            +Dictionary<string, ResourceConfig> configs
        }
            
        class ResourceConfig 
        {
            +string type
            +string name
        }
        
        ResourceConfigCollection o--> ResourceConfig 
    }

    package "Models"
    {
        class Resource
        {
            +ResourceConfig config
            +int amount
        }
    }

}

@enduml